-- Replace services with 7-service catalog (flip carousel + services page)

DELETE FROM services;

INSERT INTO services (slug, icon_key, title_it, title_en, description_it, description_en, details_it, details_en, sort_order, published) VALUES
('general-dentistry', 'clipboard-check', 'Odontoiatria generale', 'General dentistry',
 'Prevenzione, cure conservative e trattamenti per mantenere denti e gengive in salute.',
 'Prevention, restorative care, and treatments to keep teeth and gums healthy.',
 '["Controlli periodici e prevenzione","Otturazioni estetiche in composito","Devitalizzazioni e endodonzia","Estrazioni semplici","Visite di urgenza"]',
 '["Regular check-ups and prevention","Aesthetic composite fillings","Root canal therapy and endodontics","Simple extractions","Emergency visits"]', 1, true),
('dental-hygiene', 'droplets', 'Igiene dentale', 'Dental hygiene',
 'Profilassi professionale e programmi personalizzati per un sorriso pulito e sano.',
 'Professional prophylaxis and personalised programmes for a clean, healthy smile.',
 '["Detartrasi e pulizia professionale","Lucidatura e rimozione delle macchie","Programmi di richiamo personalizzati","Educazione all''igiene orale","Prevenzione delle malattie gengivali"]',
 '["Scaling and professional cleaning","Polishing and stain removal","Personalised recall programmes","Oral hygiene education","Gum disease prevention"]', 2, true),
('gum-treatment', 'heart-pulse', 'Cura delle gengive', 'Gum treatment',
 'Diagnosi e terapie per gengiviti e parodontite, con follow-up dedicato.',
 'Diagnosis and therapy for gingivitis and periodontitis, with dedicated follow-up.',
 '["Diagnosi e trattamento delle gengiviti","Terapia parodontale non chirurgica","Levigatura radicolare","Chirurgia parodontale","Mantenimento parodontale"]',
 '["Diagnosis and treatment of gingivitis","Non-surgical periodontal therapy","Root planing","Periodontal surgery","Periodontal maintenance"]', 3, true),
('implants', 'bone', 'Implantologia', 'Implants',
 'Impianti osteointegrati e riabilitazioni fisse per sostituire i denti mancanti.',
 'Osseointegrated implants and fixed rehabilitations to replace missing teeth.',
 '["Impianti dentali in titanio","Protesi fisse su impianti","Pianificazione digitale","Riabilitazioni complete","All-on-4 e soluzioni su misura"]',
 '["Titanium dental implants","Fixed implant prosthetics","Digital planning","Full rehabilitations","All-on-4 and tailored solutions"]', 4, true),
('cosmetic-dentistry', 'gem', 'Odontoiatria estetica', 'Cosmetic dentistry',
 'Sbiancamento, faccette e ricostruzioni per armonizzare e valorizzare il sorriso.',
 'Whitening, veneers, and reconstructions to harmonise and enhance your smile.',
 '["Sbiancamento professionale","Faccette estetiche in ceramica","Ricostruzioni estetiche","Armonizzazione del sorriso","Risultati naturali e duraturi"]',
 '["Professional teeth whitening","Aesthetic ceramic veneers","Cosmetic reconstructions","Smile harmonisation","Natural, lasting results"]', 5, true),
('oral-surgery', 'scissors', 'Chirurgia orale', 'Oral surgery',
 'Interventi chirurgici mirati, inclusi denti del giudizio e procedure pre-protesiche.',
 'Targeted surgical procedures, including wisdom teeth and pre-prosthetic care.',
 '["Estrazione denti del giudizio","Estrazioni complesse","Chirurgia pre-protesica","Asportazione di cisti","Procedure mininvasive"]',
 '["Wisdom tooth extraction","Complex extractions","Pre-prosthetic surgery","Cyst removal","Minimally invasive procedures"]', 6, true),
('snoring-sleep-apnea', 'bed-double', 'Russamento e apnee notturne', 'Snoring & sleep apnea',
 'Valutazione e dispositivi personalizzati per migliorare il sonno e la respirazione notturna.',
 'Assessment and custom devices to improve sleep and nighttime breathing.',
 '["Valutazione del russamento","Dispositivi MAD personalizzati","Approccio multidisciplinare","Miglioramento della qualità del sonno","Follow-up e adattamento del dispositivo"]',
 '["Snoring assessment","Custom MAD devices","Multidisciplinary approach","Improved sleep quality","Device follow-up and adjustment"]', 7, true);
